#line 2 "Lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
static yyconst short int yy_acclist[268] =
    {   0,
       82,   80,   81,    1,   80,   81,    1,   81,   80,   81,
       55,   80,   81,   36,   80,   81,   50,   80,   81,   80,
       81,    4,   80,   81,    5,   80,   81,   33,   80,   81,
       32,   80,   81,   12,   80,   81,   31,   80,   81,   10,
       80,   81,   34,   80,   81,   61,   80,   81,   61,   80,
       81,   14,   80,   81,   13,   80,   81,    8,   80,   81,
       37,   80,   81,    9,   80,   81,   60,   80,   81,    6,
       80,   81,    7,   80,   81,   35,   80,   81,   60,   80,
       81,   60,   80,   81,   60,   80,   81,   60,   80,   81,
       60,   80,   81,   60,   80,   81,   60,   80,   81,   60,

       80,   81,   60,   80,   81,   60,   80,   81,   60,   80,
       81,   60,   80,   81,   60,   80,   81,   60,   80,   81,
        2,   80,   81,   51,   80,   81,    3,   80,   81,   56,
       80,   81,   77,   81,   78,   81,   77,   81,   72,   81,
       73,   81,   72,   81,   69,   43,   70,   40,   38,   75,
       39,   49,   64,   41,   63,   61,   15,   52,   45,   44,
       46,   53,   60,   76,   42,   60,   60,   16,   60,   60,
       60,   60,   60,   60,   60,   23,   60,   60,   60,   60,
       48,   60,   60,   60,   60,   60,   60,   79,   74,   75,
       75,   11,   63,   65,   62,   47,   60,   60,   60,   21,

       60,   60,   18,   60,   60,   60,   60,   57,   60,   54,
       60,   60,   60,   60,   60,   60,   60,   75,   71,   64,
       63,   67,   66,   60,   26,   60,   60,   60,   22,   60,
       60,   60,   60,   24,   60,   59,   60,   60,   60,   66,
       68,   30,   60,   60,   58,   60,   60,   27,   60,   60,
       60,   19,   60,   17,   60,   66,   25,   60,   60,   20,
       60,   29,   60,   60,   28,   60,   67
    } ;

static yyconst short int yy_accept[214] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   11,   14,   17,   20,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   82,   85,   88,   91,   94,
       97,  100,  103,  106,  109,  112,  115,  118,  121,  124,
      127,  130,  133,  135,  137,  139,  141,  143,  145,  145,
      146,  146,  147,  147,  148,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  157,  157,  157,  158,  159,  160,
      161,  162,  163,  164,  164,  165,  166,  167,  168,  170,
      171,  172,  173,  174,  175,  176,  178,  179,  180,  181,

      183,  184,  185,  186,  187,  188,  188,  189,  189,  190,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      191,  192,  192,  193,  193,  194,  194,  194,  195,  195,
      196,  198,  199,  200,  202,  203,  205,  206,  207,  208,
      210,  212,  213,  214,  215,  216,  217,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  219,  219,  220,  220,
      221,  221,  222,  223,  224,  224,  225,  227,  228,  229,
      231,  232,  233,  234,  236,  238,  239,  240,  240,  240,
      240,  241,  241,  241,  242,  244,  245,  247,  248,  250,
      251,  252,  254,  256,  256,  256,  257,  259,  260,  262,

      264,  264,  265,  265,  267,  267,  267,  267,  267,  267,
      267,  268,  268
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       29,   30,   29,   29,   29,   29,   29,   29,   31,   32,
       29,   29,   29,   29,   29,   29,   29,   33,   29,   29,
       34,   35,   36,   37,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   29,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       29,   56,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    1,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    4,    4,
        4,    5,    4,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        5,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[228] =
    {   0,
        0,    0,   60,   61,   62,   63,  404,  405,  405,  405,
       65,  405,  379,  405,   58,  405,  405,  378,  377,  405,
       53,   53,  376,   62,   67,  378,  405,   51,  374,   66,
        0,   68,  405,  373,  347,  343,  344,   57,   63,  343,
      349,  341,   38,  338,  347,   58,  339,  342,  405,  405,
      405,  405,  405,  405,   83,  405,  405,   87,  103,  405,
      136,  405,  107,  405,  192,  405,  405,   87,  405,  370,
      106,  405,  109,  141,  185,  369,  405,  405,  405,  405,
      405,  405,    0,   88,  405,  405,  343,  341,    0,  329,
      340,  332,  327,  329,  323,    0,  336,  327,  320,    0,

       25,  331,  317,  317,  324,  107,  405,  108,  405,  366,
      145,  188,  309,    0,  364,  219,  233,  307,    0,  331,
      103,  128,  405,  200,  237,  247,  158,  206,    0,  170,
        0,  326,  321,    0,  309,    0,  321,  310,  321,    0,
        0,  316,  302,  307,  313,  308,  304,  253,  112,    0,
        0,  265,  137,    0,    0,  271,  165,  405,  214,  257,
      262,  271,  274,   98,  279,  255,  250,  253,  239,    0,
      239,  248,  226,    0,    0,  222,  227,  202,  200,  217,
      185,  288,  291,  294,    0,  206,    0,  199,    0,  189,
      191,    0,    0,  171,  297,  300,    0,  172,    0,    0,

      189,  165,  151,    0,  136,  134,  133,  139,  124,  116,
      405,  405,  320,  325,  330,  335,  338,  343,  347,  166,
      164,  163,  155,  150,  132,  112,  348
    } ;

static yyconst short int yy_def[228] =
    {   0,
      212,    1,  213,  213,  214,  214,  212,  212,  212,  212,
      215,  212,  212,  212,  216,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      217,  212,  212,  212,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  215,  212,
      212,  212,  216,  212,  212,  212,  212,  218,  212,  212,
      212,  212,  212,  212,  212,  219,  212,  212,  212,  212,
      212,  212,  217,  212,  212,  212,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  212,  212,  212,  212,  212,
      215,  215,  212,  220,  212,  216,  216,  212,  221,  218,
      218,  212,  212,  212,  212,  212,  212,  212,  222,  219,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  215,  215,  223,
      224,  216,  216,  225,  226,  218,  212,  212,  212,  212,
      212,  212,  222,  227,  212,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  223,  225,  212,
      227,  212,  212,  212,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  212,  212,  212,  217,  217,  217,  217,

      212,  217,  212,  217,  212,  212,  212,  212,  212,  212,
      212,    0,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212
    } ;

static yyconst short int yy_nxt[468] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   31,
       31,   31,   31,   32,    8,   33,   34,   35,   36,   31,
       37,   38,   39,   40,   31,   41,   31,   42,   43,   44,
       31,   45,   31,   46,   47,   31,   48,   31,   49,   50,
       51,   52,   54,   54,   57,   57,   64,   68,   70,   60,
       71,   71,   71,   78,   79,  142,   69,   73,  143,   74,
       74,   74,   73,   98,   74,   74,   74,   99,   75,   81,
       82,   84,   65,   75,   76,   55,   55,   58,   58,   61,

       92,   85,  102,   75,   90,   91,  106,   60,   75,  103,
      108,   84,   93,  121,   63,   64,   60,   94,  107,   76,
      122,   85,  109,   71,   71,   71,  125,  125,  125,  182,
      106,  108,  124,  156,  179,  126,  212,   61,   59,  110,
       59,   65,  107,  109,   59,   64,   61,  124,  182,   60,
      126,  157,   59,  111,  111,  112,   73,  178,   74,   74,
       74,  158,  148,  148,  148,  163,  155,   75,  151,  211,
       59,   65,  210,   59,   59,  128,  128,  128,   59,   61,
      209,  208,   75,  207,   59,  164,  206,   59,  157,   59,
      113,   59,   60,  114,   63,  115,   63,  127,  158,  127,

       63,  165,  128,  128,  128,  149,  149,  149,  205,  116,
      116,  117,  159,  204,  159,  203,  182,  160,  160,  160,
      165,  202,   61,  128,  128,  128,   63,   64,  201,   63,
       63,  160,  160,  160,   63,  182,  152,  152,  152,  200,
       63,   64,  199,   63,  198,   63,  118,   63,  197,  119,
      153,  153,  153,   65,  125,  125,  125,   60,  194,  161,
       63,  161,   59,  126,  162,  162,  162,   65,  193,  192,
      149,  149,  149,   64,  160,  160,  160,  191,  126,  162,
      162,  162,  153,  153,  153,  190,  189,   61,  162,  162,
      162,  183,  188,  183,  187,  186,  184,  184,  184,   65,

      195,  185,  195,  180,  212,  196,  196,  196,  184,  184,
      184,  184,  184,  184,  196,  196,  196,  196,  196,  196,
       53,   53,   53,   53,   53,   56,   56,   56,   56,   56,
       59,   59,   59,   59,   59,   63,   63,   63,   63,   63,
       83,   83,   83,  120,  120,  120,  120,  120,  130,  130,
      181,  177,  181,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  212,  154,   63,  150,   59,  147,
      146,  145,  144,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  129,  123,  105,  104,  101,  100,
       97,   96,   95,   89,   88,   87,   86,   80,   77,   72,

       67,   66,   62,  212,    7,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212
    } ;

static yyconst short int yy_chk[468] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,   15,   21,   22,   11,
       22,   22,   22,   28,   28,  101,   21,   24,  101,   24,
       24,   24,   25,   43,   25,   25,   25,   43,   24,   30,
       30,   32,   15,   25,   24,    3,    4,    5,    6,   11,

       39,   32,   46,   24,   38,   38,   55,   59,   25,   46,
       58,   84,   39,   68,  226,   63,  149,   39,   55,   24,
       68,   84,   58,   71,   71,   71,   73,   73,   73,  164,
      106,  108,   71,  121,  225,   73,  121,   59,   61,   61,
       61,   63,  106,  108,   61,  153,  149,   71,  164,  111,
       73,  122,  224,   61,   61,   61,   74,  223,   74,   74,
       74,  122,  111,  111,  111,  222,  221,   74,  220,  210,
       61,  153,  209,   61,   61,  127,  127,  127,   61,  111,
      208,  207,   74,  206,   61,  130,  205,   61,  157,   61,
       61,   61,  112,   61,   65,   65,   65,   75,  157,   75,

       65,  130,   75,   75,   75,  112,  112,  112,  203,   65,
       65,   65,  124,  202,  124,  201,  181,  124,  124,  124,
      130,  198,  112,  128,  128,  128,   65,  116,  194,   65,
       65,  159,  159,  159,   65,  181,  116,  116,  116,  191,
       65,  117,  190,   65,  188,   65,   65,   65,  186,   65,
      117,  117,  117,  116,  125,  125,  125,  148,  180,  126,
      179,  126,  178,  125,  126,  126,  126,  117,  177,  176,
      148,  148,  148,  152,  160,  160,  160,  173,  125,  161,
      161,  161,  152,  152,  152,  172,  171,  148,  162,  162,
      162,  165,  169,  165,  168,  167,  165,  165,  165,  152,

      182,  166,  182,  163,  156,  182,  182,  182,  183,  183,
      183,  184,  184,  184,  195,  195,  195,  196,  196,  196,
      213,  213,  213,  213,  213,  214,  214,  214,  214,  214,
      215,  215,  215,  215,  215,  216,  216,  216,  216,  216,
      217,  217,  217,  218,  218,  218,  218,  218,  219,  219,
      227,  147,  227,  146,  145,  144,  143,  142,  139,  138,
      137,  135,  133,  132,  120,  118,  115,  113,  110,  105,
      104,  103,  102,   99,   98,   97,   95,   94,   93,   92,
       91,   90,   88,   87,   76,   70,   48,   47,   45,   44,
       42,   41,   40,   37,   36,   35,   34,   29,   26,   23,

       19,   18,   13,    7,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexer.l"
#define INITIAL 0
#line 2 "Lexer.l"
#include "Parser.tab.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h> //va_list

#define noyywrap
#define DEBUG

#define fileno _fileno

#define YY_USER_ACTION \
yylloc.first_line = yylloc.last_line; \
yylloc.first_column = yylloc.last_column; \
for(int i = 0; yytext[i] != '\0'; i++) { \
if(yytext[i] == '\n') { \
yylloc.last_line++; \
yylloc.last_column = 0; \
} \
else { \
yylloc.last_column++; \
} \
}

void DEBUGPRINT(char* format, ...) // должен быть хотя бы один аргумент
{
	#ifdef DEBUG 
		va_list args;
		va_start(args, format);		
		vprintf(format, args);
		va_end(args);
	#endif
}


int left_side = 0;
int right_side = 0;
/* TEST IT SECTION */

//UtfEscape
//LONGSTR_LVL


/*TODO LIST!!!*/

//To do LONGSTR
//LONGSTR_LVL add the laziness of the | ' [' .*? ']'

//(...) deleted


#define NESTEDSTR1 1
#define MANYLINESCOMMENT 2

#line 639 "Lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 "Lexer.l"

#line 792 "Lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 213 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 405 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 69 "Lexer.l"
/* Ignore */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "Lexer.l"
{ DEBUGPRINT("\nLex: FUNC_BLOCK: %s", yytext); 	return *yytext; } /* Block */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "Lexer.l"
{ DEBUGPRINT("\nLex: FUNC_BLOCK: %s", yytext); 	return *yytext; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "Lexer.l"
{ DEBUGPRINT("\nLex: ARGS_BLOCK: %s", yytext); 	return *yytext; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "Lexer.l"
{ DEBUGPRINT("\nLex: ARGS_BLOCK: %s", yytext); 	return *yytext; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "Lexer.l"
{ DEBUGPRINT("\nLex: ELEM_BLOCK: %s", yytext); 	return *yytext; } /* Element */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "Lexer.l"
{ DEBUGPRINT("\nLex: ELEM_BLOCK: %s", yytext); 	return *yytext; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "Lexer.l"
{ DEBUGPRINT("\nLex: MORE & ATTR: %s", yytext); return *yytext; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "Lexer.l"
{ DEBUGPRINT("\nLex: LESS & ATTR: %s", yytext); return *yytext; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "Lexer.l"
{ DEBUGPRINT("\nLex: DOT: %s", yytext); 		return *yytext; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "Lexer.l"
{ DEBUGPRINT("\nLex: DOTS: %s", yytext);        return DOTS; } /* Args and separators */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "Lexer.l"
{ DEBUGPRINT("\nLex: COMMA: %s", yytext);       return *yytext; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "Lexer.l"
{ DEBUGPRINT("\nLex: SEMICOLON: %s", yytext);   return *yytext; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "Lexer.l"
{ DEBUGPRINT("\nLex: COLON: %s", yytext);   	return *yytext; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "Lexer.l"
{ DEBUGPRINT("\nLex: LABEL_DFE: %s", yytext);   return LABEL_DEF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "Lexer.l"
{ DEBUGPRINT("\nLex: DO: %s", yytext); 			return DO; }	/* Looping */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "Lexer.l"
{ DEBUGPRINT("\nLex: WHILE: %s", yytext); 		return WHILE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 94 "Lexer.l"
{ DEBUGPRINT("\nLex: FOR: %s", yytext); 		return FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 95 "Lexer.l"
{ DEBUGPRINT("\nLex: UNTIL: %s", yytext); 		return UNTIL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 96 "Lexer.l"
{ DEBUGPRINT("\nLex: REPEAT: %s", yytext); 		return REPEAT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "Lexer.l"
{ DEBUGPRINT("\nLex: END: %s", yytext); 		return END; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 98 "Lexer.l"
{ DEBUGPRINT("\nLex: GOTO: %s", yytext); 		return GOTO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "Lexer.l"
{ DEBUGPRINT("\nLex: IF: %s", yytext); 			return IF; }	/* Statements */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "Lexer.l"
{ DEBUGPRINT("\nLex: THEN: %s", yytext); 		return THEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "Lexer.l"
{ DEBUGPRINT("\nLex: ELSEIF: %s", yytext); 		return ELSEIF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "Lexer.l"
{ DEBUGPRINT("\nLex: ELSE: %s", yytext); 		return ELSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "Lexer.l"
{ DEBUGPRINT("\nLex: LOCAL: %s", yytext); 		return LOCAL; } /* Values */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "Lexer.l"
{ DEBUGPRINT("\nLex: ELSE: %s", yytext); 		return FUNCTION; } /* Function */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "Lexer.l"
{ DEBUGPRINT("\nLex: RETURN: %s", yytext); 		return RETURN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "Lexer.l"
{ DEBUGPRINT("\nLex: BREAK: %s", yytext); 		return BREAK; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "Lexer.l"
{ DEBUGPRINT("\nLex: MINUS: %s", yytext); 			return MINUS; } /* UNOP and BINOP */ 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 117 "Lexer.l"
{ DEBUGPRINT("\nLex: PLUS: %s", yytext); 			return BINOP; } /* Digit operators */
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "Lexer.l"
{ DEBUGPRINT("\nLex: TIMES: %s", yytext); 			return BINOP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 119 "Lexer.l"
{ DEBUGPRINT("\nLex: DIVIDE: %s", yytext); 			return BINOP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 120 "Lexer.l"
{ DEBUGPRINT("\nLex: POWER: %s", yytext); 			return BINOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 121 "Lexer.l"
{ DEBUGPRINT("\nLex: MODULO: %s", yytext);      	return BINOP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "Lexer.l"
{ DEBUGPRINT("\nLex: ASSIGN: %s", yytext);			return *yytext; } /* Combined binops */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 125 "Lexer.l"
{ DEBUGPRINT("\nLex: PLUS_ASSIGN: %s", yytext); 	return BINOP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 126 "Lexer.l"
{ DEBUGPRINT("\nLex: MINUS_ASSIGN: %s", yytext); 	return BINOP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "Lexer.l"
{ DEBUGPRINT("\nLex: TIMES_ASSIGN: %s", yytext); 	return BINOP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 128 "Lexer.l"
{ DEBUGPRINT("\nLex: DIVIDE_ASSIGN: %s", yytext); 	return BINOP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 129 "Lexer.l"
{ DEBUGPRINT("\nLex: POW_ASSIGN: %s", yytext); 		return BINOP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "Lexer.l"
{ DEBUGPRINT("\nLex: MODULO_ASSIGN: %s", yytext);   return BINOP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "Lexer.l"
{ DEBUGPRINT("\nLex: EQUALS: %s", yytext);      	return BINOP; } /* Logic binary operators */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "Lexer.l"
{ DEBUGPRINT("\nLex: LESS_EQUALS: %s", yytext); 	return BINOP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "Lexer.l"
{ DEBUGPRINT("\nLex: MORE_EQUALS: %s", yytext); 	return BINOP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "Lexer.l"
{ DEBUGPRINT("\nLex: AND: %s", yytext); 			return BINOP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "Lexer.l"
{ DEBUGPRINT("\nLex: OR: %s", yytext); 				return BINOP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "Lexer.l"
{ DEBUGPRINT("\nLex: CONCAT: %s", yytext); 			return BINOP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "Lexer.l"
{ DEBUGPRINT("\nLex: AND: %s", yytext); 			return BINOP; } /* Bitwise binary operators */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 142 "Lexer.l"
{ DEBUGPRINT("\nLex: OR: %s", yytext); 				return BINOP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "Lexer.l"
{ DEBUGPRINT("\nLex: SHIFT_RIGHT: %s", yytext); 	return BINOP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "Lexer.l"
{ DEBUGPRINT("\nLex: SHIFT_LEFT: %s", yytext); 		return BINOP; } /* XOR is already defined */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 147 "Lexer.l"
{ DEBUGPRINT("\nLex: NOT: %s", yytext); 			return UNOP; } /* Unary operators */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 148 "Lexer.l"
{ DEBUGPRINT("\nLex: #: %s", yytext); 				return UNOP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 149 "Lexer.l"
{ DEBUGPRINT("\nLex: MORE_EQUALS: %s", yytext); 	return UNOP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "Lexer.l"
{ DEBUGPRINT("\nLex: operation NIL: %s", yytext); 	return NIL; } /* Keyworded values */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 153 "Lexer.l"
{ DEBUGPRINT("\nLex: operation FALSE: %s", yytext); return FALSE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 154 "Lexer.l"
{ DEBUGPRINT("\nLex: operation TRUE: %s", yytext); 	return TRUE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "Lexer.l"
{ DEBUGPRINT("\nLex: NAME: %s", yytext); 			return NAME; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 160 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral INT: %s", yytext);		return INT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral HEX: %s", yytext); 	return HEX; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral FLOAT_1: %s", yytext); return FLOAT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 164 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral FLOAT_2: %s", yytext); return FLOAT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 165 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral FLOAT_3: %s", yytext); return FLOAT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral HEX_FLOAT_1: %s", yytext); return HEX_FLOAT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 168 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral HEX_FLOAT_2: %s", yytext); return HEX_FLOAT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "Lexer.l"
{ DEBUGPRINT("\nLex: Numeral HEX_FLOAT_3: %s", yytext); return HEX_FLOAT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "Lexer.l"
{ DEBUGPRINT("\nLex: TWOQSTRING: %s", yytext); return TWOQSTRING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 172 "Lexer.l"
{ DEBUGPRINT("\nLex: ONEQSTRING: %s", yytext); return ONEQSTRING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "Lexer.l"
{	left_side = strlen(yytext) - 2;
														DEBUGPRINT("\nLex: LINES_COMMENT count left: %d, %s", left_side, yytext);
														BEGIN(MANYLINESCOMMENT); 
													}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 178 "Lexer.l"
{ DEBUGPRINT("\nLex: In_comment1 %s", yytext);   }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 179 "Lexer.l"
{ DEBUGPRINT("\nLex: In_comment2 %s", yytext);   }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 180 "Lexer.l"
{	right_side = strlen(yytext);
														DEBUGPRINT("\nLex: LINES_COMMENT count right: %d, %s", right_side, yytext);
														BEGIN(INITIAL);
														if (right_side == left_side)
														{ /* ignore */ }
														else { DEBUGPRINT("\nLex: incorrect many_lines_comment"); exit(-20); }  
													}		
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 188 "Lexer.l"
{ DEBUGPRINT("\nLex: ONELINE%s", yytext);/* one line comment */}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 190 "Lexer.l"
{	left_side = strlen(yytext);  
														DEBUGPRINT("\nLex: LONG_STR count left: %d, %s", left_side, yytext); 
														BEGIN(NESTEDSTR1);
													}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 194 "Lexer.l"
{ }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 195 "Lexer.l"
{ }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 196 "Lexer.l"
{	right_side = strlen(yytext);  
														DEBUGPRINT("\nLex: LONG_STR count right: %d, %s", right_side, yytext); 
														BEGIN(INITIAL); 
														if (right_side == left_side) return LONGSTRING;
													}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 201 "Lexer.l"
{
							DEBUGPRINT("\nLex: unknown: %s", yytext);
							return yytext[0]; 
						}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 206 "Lexer.l"
ECHO;
	YY_BREAK
#line 1307 "Lexer.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NESTEDSTR1):
			case YY_STATE_EOF(MANYLINESCOMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 213 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 213 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 212);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 206 "Lexer.l"
